version: '4'
services:
  web:
    container_name: philanthrotrees
    image: hegelocampus/philanthrotrees
    build:
      context: .
      dockerfile: Dockerfile
    command: node index.js
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    healthcheck:
      test: curl --fail -s http://localhost:3000/ || exit 1
      interval: 5m
      timeout: 10s
      retries: 3

